<?php
if (isset($var->tasting)) {
    $tasting = $var->tasting;
} else {
    http_response_code(404);
    die();
}

?>
<style>
.card {
    margin-bottom: 15px;
    margin-top: 10px;
}
</style>

<div class="container-fluid d-flex align-items-center flex-column bg-secondary" style=" padding:40px;">
    <!-- Titre de la degustation-->
    <h1 class="masthead2-heading text-uppercase mb-0"><?php echo $tasting->title ?></h1>
    <!-- Icon Divider-->
    <div class="divider-custom divider-light">
        <div class="divider-custom-line"></div>
        <div class="divider-custom-icon">
            <i class="fas fa-star"></i>
        </div>
        <div class="divider-custom-line"></div>
    </div>
    <!-- Nom du degustateur-->
    <p class="masthead2-subheading font-weight-light mb-0">
        <?php echo $tasting->userName . " - " . $tasting->beerName . " - " ?> <a
            href="<?php echo str_replace("#id#", $tasting->beerStyleId, PAGE_BEER_STYLE) ?>"><?php echo $tasting->beerStyleTitle ?></a>
    </p>
</div>

<div class="row">
    <div class="col-12">
        <div class="card no-border" style="padding: 20px;">
            <!-- Content section -->
            <!-- Bottle Inspection -->
            <div class="row">
                <div class="row">
                    <div class="col-12">
                        <p><?php echo $tasting->total ?> / 50</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="stars" data-rating="<?php echo $tasting->total / 10 ?>" data-num-stars="5">
                        </div>
                        <div data-toggle="tooltip" data-placement="top"
                            title="<?php echo App::getComment($tasting->score['label']); ?>">
                            <?php echo $tasting->score['label'] ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card no-border">
                        <div class="card-header">
                            <div class="row">
                                <h3 class="col-8"><?php echo bottleInspection ?></h3>
                                <span class="col-4">
                                    <?php
                                    if ($tasting->isBottleOk == 1) {
                                    ?>
                                    <i class="fas fa-thumbs-up" style="color: green;"></i>
                                    <?php
                                    } else {
                                    ?>
                                    <i class="fas fa-thumbs-down" style="color: red;"></i>
                                    <?php
                                    }
                                    ?>
                                </span>
                            </div>
                        </div>
                        <div class="card-body">
                            <?php echo $tasting->bottleInspectionComment ?>
                        </div>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-condensed alignLeft">
                            <thead>
                                <th><?php echo criteria ?></th>
                                <th><?php echo score ?></th>
                                <th><?php echo comments ?></th>
                            </thead>
                            <tbody>
                                <tr class="score" data-type="table"
                                    data-score="<?php echo ($tasting->aromaScore * 10) / 10 ?>">
                                    <td><?php echo aroma ?></td>
                                    <td><?php echo $tasting->aromaScore ?> /12</td>
                                    <td><?php echo $tasting->aromaComment ?></td>
                                </tr>
                                <tr class="score" data-type="table"
                                    data-score="<?php echo ($tasting->appearanceScore * 10) / 3 ?>">
                                    <td><?php echo appearance ?></td>
                                    <td><?php echo $tasting->appearanceScore ?> /3</td>
                                    <td><?php echo $tasting->appearanceComment ?></td>
                                </tr>
                                <tr class="score" data-type="table"
                                    data-score="<?php echo $tasting->flavorScore / 2 ?>">
                                    <td><?php echo flavor ?></td>
                                    <td><?php echo $tasting->flavorScore ?> /20</td>
                                    <td><?php echo $tasting->flavorComment ?></td>
                                </tr>
                                <tr class="score" data-type="table"
                                    data-score="<?php echo ($tasting->mouthfeelScore * 10) / 5 ?>">
                                    <td><?php echo mouthfeel ?></td>
                                    <td><?php echo $tasting->mouthfeelScore ?> /5</td>
                                    <td><?php echo $tasting->mouthfeelComment ?></td>
                                </tr>
                                <tr class="score" data-type="table" data-score="<?php echo $tasting->overallScore ?>">
                                    <td><?php echo overallImpression ?></td>
                                    <td><?php echo $tasting->overallScore ?> /10</td>
                                    <td><?php echo $tasting->overallComment ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class=" row">
                <div class="col-12">
                    <div class="card no-border">
                        <div class="card-header">
                            <h3 class=""><?php echo offFlavors ?></h3>
                        </div>
                        <div class="card-body">
                            <?php
                            if (!empty($tasting->offFlavors->getOffFlavors())) {
                            ?>
                            <ul class="list-group">
                                <?php
                                    foreach ($tasting->offFlavors->getOffFlavors() as $offFlavor) {
                                    ?>
                                <li class="list-group-item" data-toggle="tooltip" data-placement="top"
                                    title="<?php echo App::getOffFlavorText(App::renameOffFlavor($offFlavor)); ?>">
                                    <?php echo App::renameOffFlavor($offFlavor) ?>
                                </li>
                                <?php
                                    }
                                    ?>
                            </ul>
                            <?php
                            }
                            ?>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class=" row">
            <div class="col-4">
                <!-- Stylistic Accuracy -->
                <div class="card no-border">
                    <div class="card-header">
                        <h3><?php echo stylisticAccuracy ?></h3>
                    </div>
                    <div class="card-body" data-toggle="tooltip" data-placement="top"
                        title="<?php echo STYLISTIC_MESSAGE_START . ' ' . TO . ' ' . STYLISTIC_MESSAGE_END ?>">
                        <div class="stars" data-rating="<?php echo $tasting->stylisticAccuracy  ?>" data-num-stars="5">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <!-- Technical Merit -->
                <div class="card no-border">
                    <div class="card-header">
                        <h3><?php echo technicalMerit ?> </h3>
                    </div>
                    <div class="card-body" data-toggle="tooltip" data-placement="top"
                        title="<?php echo TECHNICALMERIT_MESSAGE_START . ' ' . TO . ' ' . TECHNICALMERIT_MESSAGE_END ?>">
                        <div class="stars" data-rating="<?php echo $tasting->technicalMerit ?>" data-num-stars="5">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <!-- Intangibles -->
                <div class="card no-border">
                    <div class="card-header">
                        <h3><?php echo intangibles ?></h3>
                    </div>
                    <div class="card-body" data-toggle="tooltip" data-placement="top"
                        title="<?php echo INTANGIBLES_MESSAGE_START . ' ' . TO . ' ' . INTANGIBLES_MESSAGE_END ?>">
                        <div class="stars" data-rating="<?php echo $tasting->intangibles ?>" data-num-stars="5">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>