<?php
$connectedUser = Session::getConnectedUser();
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="<?php echo SITE_URL . ASSET_FOLDER . "img/favicon.ico" ?>?v=3" />
    <!-- Bootstrap Icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!--iconify -->
    <script src="https://code.iconify.design/2/2.0.3/iconify.min.js"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic"
        rel="stylesheet" type="text/css" />
    <!-- SimpleLightbox plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="<?php echo SITE_URL . CSS_FOLDER . "styles.css" ?>" rel="stylesheet" />
    <!-- CSS for jQuery password complexity check plugin-->
    <link rel="stylesheet" href="<?php echo SITE_URL . CSS_FOLDER . "jquery.passwordRequirements.css" ?>" />
    <title><?php echo $var->title ?></title>
    <script src=" https://www.google.com/recaptcha/api.js" async defer>
    </script>
    <!-- font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Epilogue&display=swap" rel="stylesheet">


    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!--  Load jQuery password complexity check plugin-->
    <script src="<?php echo SITE_URL . JS_FOLDER . "jquery.passwordRequirements.min.js" ?>"></script>
    <script src=" <?php echo SITE_URL . JS_FOLDER . "scripts.js" ?>"></script>
    <script>
    $(function() {
        $('.stars').stars();
    });
    $(function() {
        $('.score').score();
    });
    </script>
</head>

<body>
    <?php
    /* Cas ou l'utilisateur n'est pas connecté, affichez le menu adequat et le content*/
    if ($connectedUser == null) {
    ?>
    <div class="d-flex flex-column min-vh-100">
        <?php echo App::get_partial('nav_1', array()); ?>
        <main class="flex-fill">
            <?php
                echo $var->content;
                ?>
        </main>
        <?php echo App::get_partial('footer', array()); ?>
    </div>
    <?php
    } else {
    ?>
    <div class="container-fluid overflow-hidden">
        <div class="row vh-100 overflow-auto">
            <div class="col-12 col-sm-3 col-xl-2 px-sm-2 px-0  d-flex bg-beer sticky-top">
                <?php echo  App::get_partial('nav_2', array()) ?>
            </div>
            <div class="col d-flex flex-column h-sm-100 background">
                <main class="row overflow-auto">
                    <div class="col pt-4">
                        <?php
                            if ($var->breadCrumbs) {
                            ?>
                        <nav aria-label="breadcrumb">

                            <ol class="breadcrumb">
                                <?php
                                        foreach ($var->breadCrumbs as $key => $link) {
                                            if ($link) {
                                                echo '<li class="breadcrumb-item"><a href=' . $link . '>' . $key . '</a></li>';
                                            } else {
                                                echo '<li class="breadcrumb-item active aria-current="page">' . $key . '</li>';
                                            }
                                        }
                                        ?>
                            </ol>
                        </nav>

                        <?php
                            }
                            ?>
                        <?php echo $var->content ?>
                    </div>
                </main>
                <?php echo App::get_partial('footer', array()); ?>
            </div>
        </div>
    </div>
    <?php   }  ?>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    <script src="<?php echo SITE_URL . JS_FOLDER ?>bootstrap-show-password.js"></script>
    </script>
</body>

</html>