<div class="row">
    <div class="col-12">
        <div class="card no-border">
            <div class="card-header">
                <h2><?php echo beerStyles ?></h2>
                <p><?php echo textBeerStyles ?></p>
            </div>
            <div class="card-body">
                <ul class="list-group">
                    <?php
                    foreach ($var->beerStyles as $beerStyle) {
                    ?>
                    <a href="<?php echo str_replace("#id#", $beerStyle->id, PAGE_BEER_STYLE) ?>"
                        class="list-group-item list-group-item-action"><?php echo $beerStyle->title ?>
                        <?php
                            if (Session::getConnectedUser()->isAdmin) {
                            ?>
                        <span>
                            <button data-id="<?php echo $beerStyle->id ?>"
                                class="btn btn-danger delete-beer-style-btn"><?php echo delete  ?>
                            </button>
                        </span>
                        <?php
                            }
                            ?>
                    </a>
                    <?php
                    }
                    ?>
                </ul>
            </div>
            <div class="mx-auto">
                <?php
                echo App::get_partial(
                    PARTIAL_PAGINATION_V5,
                    array(
                        'pages' => $var->pages,
                        'count' => $var->count,
                        'page' => $var->page,
                    )
                )
                ?>
            </div>
        </div>

    </div>
</div>

<script>
$(document).ready(function() {
    $(".delete-beer-style-btn").click(function(e) {
        e.preventDefault();
        if (!confirm("<?php echo deleteBeerStyleConfirmationMessage ?>")) {
            return false;
        } else {
            $id = $(this).data("id");
            $url = "<?php echo PAGE_BEER_STYLE_DELETE  ?>"
            window.location.href = $url.replace("#id#", $id);
        }
    });
});
</script>