<?php
$beerStyle = $var->beerStyle;
?>
<div class="row">
    <div class="col-12">
        <div class="card no-border">
            <div class="card-header">
                <h2><?php echo $beerStyle->title ?></h2>
            </div>
            <div class="card-body bg-card">
                <div class="row">
                    <div class="col-12">
                        <div class="card no-border">
                            <div class="card-header">
                                <?php echo aroma ?>
                            </div>
                            <div class="card-body">
                                <?php echo $beerStyle->aroma ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row top">
                    <div class="col-12">
                        <div class="card no-border">
                            <div class="card-header">
                                <?php echo appearance ?>
                            </div>
                            <div class="card-body">
                                <?php echo $beerStyle->appearance ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row top">
                    <div class="col-12">
                        <div class="card no-border">
                            <div class="card-header">
                                <?php echo flavor ?>
                            </div>
                            <div class="card-body">
                                <?php echo $beerStyle->flavor ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row top">
                    <div class="col-12">
                        <div class="card no-border">
                            <div class="card-header">
                                <?php echo body ?>
                            </div>
                            <div class="card-body">
                                <?php echo $beerStyle->body ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row top">
                    <div class="col-12">
                        <div class="card no-border">
                            <div class="card-header">
                                <?php echo comments ?>
                            </div>
                            <div class="card-body">
                                <?php echo $beerStyle->comments ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row top">
                    <div class="col-12">
                        <div class="card no-border">
                            <div class="card-header">
                                <?php echo story ?>
                            </div>
                            <div class="card-body">
                                <?php echo $beerStyle->story ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row top">
                    <div class="col-12">
                        <div class="card no-border">
                            <div class="card-header">
                                <?php echo ingredients ?>
                            </div>
                            <div class="card-body">
                                <?php echo $beerStyle->ingredients ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row top">
                    <div class="col-12">
                        <div class="card no-border">
                            <div class="card-header">
                                <?php echo stylesComparison ?>
                            </div>
                            <div class="card-body">
                                <?php echo $beerStyle->stylesComparison ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row top">
                    <div class="col-12">
                        <div class="card no-border">
                            <div class="card-header">
                                <?php echo commercialExamples ?>
                            </div>
                            <div class="card-body">
                                <?php echo $beerStyle->commercialExamples ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>