        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold"><?php echo homeTitle ?></h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5"><?php echo homeDesc1 ?>
                        </p>
                        <a class="btn btn-primary btn-xl"
                            href="<?php echo PAGE_TASTINGS_VISITOR ?>"><?php echo showTastings ?></a>
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="page-section bg-primary" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0"><?php echo saveTasting ?></h2>
                        <hr class="divider divider-light" />
                        <p class="text-white-75 mb-4"><?php echo homeDesc2 ?>
                        </p>
                        <a class="btn btn-light btn-xl" href="<?php echo PAGE_SIGNUP ?>"><?php echo signUp ?></a>
                    </div>
                </div>
            </div>
        </section>