<style>
#notfound {
    position: relative;
    height: 100vh;
}

#notfound .notfound-bg {
    position: absolute;
    width: 100%;
    height: 100%;
    background-image: url('<?php echo ASSET_FOLDER . '/img/beer-error.jpg'; ?>');
    background-size: cover;
}

#notfound .notfound {
    position: absolute;
    left: 50%;
    top: 50%;
    -webkit-transform: translate(-50%, -50%);
    -ms-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
}

.notfound {
    max-width: 910px;
    width: 100%;
    line-height: 1.4;
    text-align: center;
}

.notfound .notfound-404 {
    position: relative;
    height: 200px;
}

.notfound .notfound-404 h1 {
    font-family: 'Montserrat', sans-serif;
    position: absolute;
    left: 50%;
    top: 50%;
    -webkit-transform: translate(-50%, -50%);
    -ms-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
    font-size: 220px;
    font-weight: 900;
    margin: 0px;
    color: red;
    text-transform: uppercase;
    letter-spacing: 10px;
}

.notfound h2 {
    font-family: 'Montserrat', sans-serif;
    font-size: 22px;
    font-weight: 700;
    text-transform: uppercase;
    color: red;
    margin-top: 20px;
    margin-bottom: 15px;
}

@media only screen and (max-width: 767px) {
    .notfound .notfound-404 h1 {
        font-size: 182px;
    }
}

@media only screen and (max-width: 480px) {
    .notfound .notfound-404 {
        height: 146px;
    }

    .notfound .notfound-404 h1 {
        font-size: 146px;
    }

    .notfound h2 {
        font-size: 16px;
    }
}
</style>
<div id="notfound">
    <div class="notfound-bg"></div>
    <div class="notfound">
        <div class="notfound-404">
            <h1>404</h1>
        </div>
        <h2><?php echo error_message; ?></h2>
        <a href="<?php echo PAGE_HOME ?>"><button class="btn btn-primary"><?php echo go_acceuil; ?></button></a>

    </div>
</div>