<?php
if (!empty($errors)) {
  foreach ($errors as $error) {
?>
<div class="alert alert-danger" role="alert">
    <?php echo $error; ?>
</div>
<?php
  }
}
?>
<!-- Alert-->
<!-- Section-->
<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card border-0 shadow rounded-3 my-5">
                <div class="card-body p-4 p-sm-5">
                    <h5 class="card-title text-center mb-5 fw-light fs-5">Mot de passe oublié</h5>
                    <form action="" method="POST">

                        <div class="form-floating mb-3">
                            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com"
                                name="email">
                            <label for="floatingInput">Email address</label>
                        </div>

                        <div class="d-grid">
                            <button class="btn btn-primary btn-login text-uppercase fw-bold"
                                type="submit">Valider</button>
                        </div>
                        <hr class="my-4">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>