<fieldset class="hidden">
    <div class="row">
        <h4><?php echo offFlavors ?></h4>
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_ACETALDEHYDE ?>"
                    name="<?php echo Tasting::IS_ACETALDEHYDE ?>" data-toggle="tooltip" data-placement="top"
                    title="<?php echo ACETALDEHYDE_MESSAGE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_ACETALDEHYDE ?>">Acetaldehyde</label>
            </div>
        </div>
        <div class="col-2"></div>
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_ALCOHOLIC ?>"
                    name="<?php echo Tasting::IS_ALCOHOLIC ?>" data-toggle="tooltip" data-placement="top"
                    title="<?php echo ALCOHOLIC_MESSAGE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_ALCOHOLIC ?>">Alcoholic</label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_ASTRINGENT ?>"
                    name="<?php echo Tasting::IS_ASTRINGENT ?>" data-toggle="tooltip" data-placement="top"
                    title="<?php echo ASTRINGENT_MESSAGE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_ASTRINGENT ?>">Astringent</label>
            </div>
        </div>
        <div class="col-2"></div>
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_DIACETYL ?>"
                    name="<?php echo Tasting::IS_DIACETYL ?>" data-toggle="tooltip" data-placement="top"
                    title="<?php echo DIACETYL_MESSAGE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_DIACETYL ?>">Diacetyl</label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_DMS ?>"
                    name="<?php echo Tasting::IS_DMS ?>" data-toggle="tooltip" data-placement="top"
                    title="<?php echo DMS_MESSAGE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_DMS ?>">DMS (dimethyl
                    sufide)</label>
            </div>
        </div>
        <div class="col-2"></div>
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_ESTERY ?>"
                    name="<?php echo Tasting::IS_ESTERY ?>" data-toggle="tooltip" data-placement="top"
                    title="<?php echo ESTERY_MESSAGE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_ESTERY ?>">Estery</label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_GRASSY ?>"
                    name="<?php echo Tasting::IS_GRASSY ?>" data-toggle="tooltip" data-placement="top"
                    title="<?php echo GRASSY_MESSAGE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_GRASSY ?>">Grassy</label>
            </div>
        </div>
        <div class="col-2"></div>
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_LIGHT_STRUCK ?>"
                    name="<?php echo Tasting::IS_LIGHT_STRUCK ?>" data-toggle="tooltip" data-placement="top"
                    title="<?php echo LIGHTSTRUCK_MESSAGE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_LIGHT_STRUCK ?>">Light-Struck</label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_METALLIC ?>"
                    name="<?php echo Tasting::IS_METALLIC ?>" data-toggle="tooltip" data-placement="top"
                    title="<?php echo METALLIC_MESSAGE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_METALLIC ?>">Metallic</label>

            </div>
        </div>
        <div class="col-2"></div>
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_MUSTY ?>"
                    name="<?php echo Tasting::IS_MUSTY ?>" data-toggle="tooltip" data-placement="top"
                    title="<?php echo MUSTY_MESSAGE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_MUSTY ?>">Musty</label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_OXIDIZED ?>"
                    name="<?php echo Tasting::IS_OXIDIZED ?>" data-toggle="tooltip" data-placement="top"
                    title="<?php echo OXIDIZED_MESSAGE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_OXIDIZED ?>">Oxidized</label>
            </div>
        </div>
        <div class="col-2"></div>
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_PHENOLIC ?>"
                    name="<?php echo Tasting::IS_PHENOLIC ?>" data-toggle="tooltip" data-placement="top"
                    title="<?php echo PHENOLIC_MESSAGE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_PHENOLIC ?>">Phenolic</label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_SOLVENT ?>"
                    name="<?php echo Tasting::IS_SOLVENT ?>" data-toggle="tooltip" data-placement="top"
                    title="<?php echo SOLVENT_MESSAGE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_SOLVENT ?>">Solvent</label>
            </div>
        </div>
        <div class="col-2"></div>
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_ACIDIC ?>"
                    name="<?php echo Tasting::IS_ACIDIC ?>" data-toggle="tooltip" data-placement="top"
                    title="<?php echo SOURACIDIC_MESSAGE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_ACIDIC ?>">Sour/Acidic</label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_SULFUR ?>"
                    name="<?php echo Tasting::IS_SULFUR ?>" data-toggle="tooltip" data-placement="top"
                    title="<?php echo SULFUR_MESSAGE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_SULFUR ?>">Sulfur</label>
            </div>
        </div>
        <div class="col-4">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_VEGETAL ?>"
                    name="<?php echo Tasting::IS_VEGETAL ?>" data-toggle="tooltip" data-placement="top"
                    title="<?php echo VEGETAL_MESSAGE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_VEGETAL ?>">Vegetal</label>
            </div>
        </div>
        <div class="col-4">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_YEASTY ?>"
                    name="<?php echo Tasting::IS_YEASTY ?>" data-toggle="tooltip" data-placement="top"
                    title="<?php echo YEASTY_MESSAGE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_YEASTY ?>">Yeasty</label>
            </div>
        </div>
    </div>
</fieldset>