<div class="row">
    <div class="col-12">
        <div class="p-3 py-5">
            <div class="justify-content-between align-items-center mb-1">
                <h4 class="text-center"><?php echo personalInformation ?></h4>
            </div>
            <!-- Action pour modifier le nom ou le prenom -->
            <form>
                <div class="alert alert-danger hidden" id="usernameErrorContainer" role="alert">
                </div>
                <div class="alert alert-success hidden" id="usernameSucessContainer" role="alert">
                </div>
                <div class="row mt-2">
                    <div class="form-floating col-md-12 mb-4">
                        <input type="text" class="form-control" placeholder="<?php echo firstName ?>" value="<?php echo Session::getConnectedUser()->firstName ?>" id="firstName" name="<?php echo User::FIRST_NAME ?>">
                        <label for="floatingInput"><?php echo firstName ?></label>
                    </div>
                    <div class="form-floating col-md-12 mb-4">
                        <input type="text" class="form-control" value="<?php echo Session::getConnectedUser()->lastName ?>" placeholder="<?php echo lastName ?>" id="lastName" name="<?php echo User::LAST_NAME ?>">
                        <label for="floatingInput"><?php echo lastName ?></label>
                    </div>
                    <div class="mt-5 text-center"><button class="btn btn-primary profile-button btn-update" id="changeUserNameBtn" type="button"><?php echo update ?></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>