<div class="row">
    <div class="col-12">
        <!-- Action pour modifier le password -->
        <form id="changePasswordForm">
            <div class="alert alert-danger hidden" id="passwordErrorContainer" role="alert">
            </div>
            <div class="alert alert-success hidden" id="passwordSuccessContainer" role="alert">
            </div>
            <div class="p-3 py-5">
                <div class="justify-content-between align-items-center experience">
                    <h4 class="text-center"><?php echo changePassword ?></h4>
                </div><br>
                <div class="row">

                    <div class="form-floating mb-4 col-md-12">
                        <input type="password" class="form-control" id="oldPassword" name="oldPassword" required>
                        <label for="floatingInput"><?php echo currentPassword ?></label>
                    </div>
                    <div class="form-floating mb-4 col-md-12">
                        <input type="password" class="form-control pr-password" id="newPassword" name="newPassword"
                            required>
                        <label for="floatingInput"><?php echo newPassword ?></label>
                    </div>
                </div>
                <div class="mt-5 text-center"><button id="changePasswordBtn" class="btn btn-primary profile-button"
                        type="button"><?php echo changePassword ?></button></div>
        </form>
    </div>
</div>