<div class="row">
    <form action="" method="post">
        <div class="p-3 py-5">
            <div class="justify-content-between align-items-center experience">
                <h4 class="text-center"><?php echo accountDeletion ?></h4>
            </div><br>
            <div class="row">
                <div class="alert alert-danger" role="alert">
                    <?php echo accountDeletionText ?>
                </div>
            </div>
            <div class="mt-5 text-center"><button class="btn btn-danger profile-button" type="button"
                    id="deleteAccountBtn"><?php echo deleteMyAccount ?></button>
            </div>
    </form>
</div>