        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="<?php echo PAGE_HOME; ?>"><?php echo APP_NAME ?></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                    aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <!-- <li class="nav-item"><a class="nav-link" href="#about">About</a></li>-->
                        <li class="nav-item"><a class="nav-link"
                                href="<?php echo PAGE_TASTINGS_VISITOR ?>"><?php echo tastings ?></a></li>
                        <li class="nav-item"><a class="nav-link"
                                href="<?php echo PAGE_SIGNIN ?>"><?php echo signIn ?></a></li>
                        <li class="nav-item"><a class="nav-link"
                                href="<?php echo PAGE_SIGNUP ?>"><?php echo signUp ?></a></li>
                    </ul>
                </div>
            </div>
        </nav>