<div
    class="d-flex flex-sm-column flex-row flex-grow-1 justify-content-around align-items-center align-items-sm-start px-3 pt-2 text-white">
    <a href="<?php echo PAGE_DASHBOARD ?>"
        class="d-flex align-items-center pb-sm-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <img src="<?php echo SITE_URL . ASSET_FOLDER . "img/logo.png" ?>" alt="TasteMyBeer-Logo" width="100"
            height="100">
    </a>
    <ul class="nav nav-pills flex-sm-column flex-row flex-nowrap flex-shrink-1 flex-sm-grow-0 flex-grow-1 mb-sm-auto mb-0 justify-content-center align-items-center align-items-sm-start"
        id="menu">
        <li class="nav-item" data-toggle="tooltip" data-placement="top" title="<?php echo add ?>">
            <a href="<?php echo PAGE_TASTINGS_ADD ?>" class="nav-link px-sm-0 px-2  text-white">
                <i class="bi-file-plus"></i><span class="ms-1 d-none d-sm-inline"><?php echo add ?> </span>
            </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="top" title="<?php echo tastings ?>">
            <a href="<?php echo PAGE_TASTINGS ?>" class="nav-link px-sm-0 px-2 text-white">
                <i class="fs-5 bi bi-eye"></i><span class="ms-1 d-none d-sm-inline"><?php echo tastings ?></span></a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="top" title="<?php echo beerStyles ?>">
            <a href="<?php echo PAGE_BEER_STYLES ?>" class="nav-link px-sm-0 px-2 text-white">
                <i class="fs-5 bi bi-card-list"></i><span
                    class="ms-1 d-none d-sm-inline"><?php echo beerStyles ?></span></a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="top" title="<?php echo myTastings ?>">
            <a href="<?php echo PAGE_USER_TASTINGS_MANAGEMENT ?>" class="nav-link px-sm-0 px-2 text-white">
                <i class="fs-5 bi bi-gear"></i><span class="ms-1 d-none d-sm-inline"><?php echo myTastings ?></span></a>
        </li>
        <?php
        if (Session::getConnectedUser()->isAdmin) {
        ?>
        <li class="nav-item" data-toggle="tooltip" data-placement="top" title="<?php echo adminArea ?>">
            <a href="<?php echo PAGE_ADMIN ?>" class="nav-link px-sm-0 px-2 text-white">
                <i class="fs-5 bi bi-sliders"></i></i><span
                    class="ms-1 d-none d-sm-inline"><?php echo adminArea ?></span></a>
        </li>
        <?php
        }
        ?>
    </ul>
    <div class="dropdown py-sm-4 mt-sm-auto ms-auto ms-sm-0 flex-shrink-1">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1"
            data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-circle fa-2x"></i>
            <span class="d-none d-sm-inline mx-1"><?php echo Session::getConnectedUser()->firstName ?></span>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
            <li data-toggle="tooltip" data-placement="top" title="<?php echo account ?>"><a class="dropdown-item"
                    href="<?php echo PAGE_PROFILE ?>"><?php echo account ?></a></li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li data-toggle="tooltip" data-placement="top" title="<?php echo logOut ?>"><a class="dropdown-item"
                    href="<?php echo PAGE_LOGOUT ?>"><?php echo logOut ?></a></li>
        </ul>
    </div>
</div>